// Phase 5 — privacy report export (SIH26171 submission evidence).
//
// Aggregates ONLY value-free sources: the session audit log (categories,
// aliases, origins, counts), the visual-stats seam (face-blur counts), and the
// manifest version. `bytesLeaked` is 0 by design — the firewall admits
// alias-only payloads and the loop never logs values — so the field is a
// constant, not a measurement (CONTRIBUTING.md Rule 22: never fabricate).

import { getAuditLog, type AuditEntry } from '../audit/log';

export interface PrivacyReport {
  generatedAt: string;
  sessionSummary: {
    tasksCompleted: number;
    totalSteps: number;
    /** Always 0 by design (alias-only egress + fail-closed firewall). */
    bytesLeaked: number;
    piiItemsProtected: number;
    /** Lower-cased categories, e.g. ['email','phone','aadhaar']. */
    categoriesProtected: string[];
    facesBlurred: number;
  };
  auditLog: AuditEntry[];
  systemInfo: {
    extensionVersion: string;
    plannerMode: string;
    onDevice: boolean;
  };
  disclaimer: string;
}

export const REPORT_DISCLAIMER =
  'Generated by PrivAgent (SIH26171). Raw values were never stored.';

const PII_DETAIL = /Detected USER_([A-Z]+) category \((\d+) instance/;

function summarizeAudit(entries: AuditEntry[]): {
  tasksCompleted: number;
  totalSteps: number;
  piiItemsProtected: number;
  categories: Set<string>;
} {
  let tasksCompleted = 0;
  let totalSteps = 0;
  let piiItemsProtected = 0;
  const categories = new Set<string>();
  for (const e of entries) {
    if (e.type === 'task_complete') tasksCompleted++;
    if (e.type === 'action_executed') totalSteps++;
    if (e.type === 'pii_detected') {
      const m = PII_DETAIL.exec(e.detail);
      if (m) {
        categories.add(m[1]!.toLowerCase());
        piiItemsProtected += Number(m[2]);
      }
    }
  }
  return { tasksCompleted, totalSteps, piiItemsProtected, categories };
}

function readFacesBlurred(): number {
  try {
    if (typeof window !== 'undefined' && window.__PRIVAGENT_VISUAL__?.faceStats) {
      return window.__PRIVAGENT_VISUAL__.faceStats.facesBlurred ?? 0;
    }
  } catch {
    // ignore - visual stats unavailable outside the panel
  }
  return 0;
}

function readExtensionVersion(): string {
  try {
    if (typeof chrome !== 'undefined' && chrome.runtime?.getManifest) {
      return chrome.runtime.getManifest().version ?? 'unknown';
    }
  } catch {
    // ignore - unavailable in tests
  }
  return 'unknown';
}

export async function generateReport(plannerMode = 'deterministic'): Promise<PrivacyReport> {
  const auditLog = await getAuditLog();
  const summary = summarizeAudit(auditLog);
  return {
    generatedAt: new Date().toISOString(),
    sessionSummary: {
      tasksCompleted: summary.tasksCompleted,
      totalSteps: summary.totalSteps,
      bytesLeaked: 0,
      piiItemsProtected: summary.piiItemsProtected,
      categoriesProtected: [...summary.categories].sort(),
      facesBlurred: readFacesBlurred(),
    },
    auditLog,
    systemInfo: {
      extensionVersion: readExtensionVersion(),
      plannerMode,
      onDevice: true,
    },
    disclaimer: REPORT_DISCLAIMER,
  };
}

/** Deterministic serializer (unit-tested for schema + zero-leak). */
export function serializeReport(report: PrivacyReport): string {
  return JSON.stringify(report, null, 2);
}

export function reportFilename(now: Date = new Date()): string {
  return `privagent-report-${now.toISOString().slice(0, 10)}.json`;
}

/**
 * Trigger a browser download of the report. Safe no-op outside a document
 * context (unit tests); returns true when a download was started.
 */
export async function exportReportAsJSON(plannerMode = 'deterministic'): Promise<boolean> {
  const report = await generateReport(plannerMode);
  try {
    if (typeof document === 'undefined') return false;
    const blob = new Blob([serializeReport(report)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = reportFilename();
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    URL.revokeObjectURL(url);
    return true;
  } catch {
    return false;
  }
}
